default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play Track"
  lane :beta do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(track: "internal")
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store
  end

  desc "Capture screenshots"
  lane :screenshots do
    capture_android_screenshots
  end
end
